// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhHaSWsOV2u7PmCsmeI8igiltJygiN2D8',
    appId: '1:728116934635:web:3101e6ad09c6e99e270bae',
    messagingSenderId: '728116934635',
    projectId: 'cleaner-application-27b56',
    authDomain: 'cleaner-application-27b56.firebaseapp.com',
    storageBucket: 'cleaner-application-27b56.firebasestorage.app',
    measurementId: 'G-4VHJ42TPKY');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhHaSWsOV2u7PmCsmeI8igiltJygiN2D8',
    appId: '1:728116934635:android:3101e6ad09c6e99e270bae',
    messagingSenderId: '728116934635',
    projectId: 'cleaner-application-27b56',
    storageBucket: 'cleaner-application-27b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhHaSWsOV2u7PmCsmeI8igiltJygiN2D8',
    appId: '1:728116934635:ios:3101e6ad09c6e99e270bae',
    messagingSenderId: '728116934635',
    projectId: 'cleaner-application-27b56',
    storageBucket: 'cleaner-application-27b56.firebasestorage.app',
    iosBundleId: 'com.example.cleanerapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhHaSWsOV2u7PmCsmeI8igiltJygiN2D8',
    appId: '1:728116934635:ios:3101e6ad09c6e99e270bae',
    messagingSenderId: '728116934635',
    projectId: 'cleaner-application-27b56',
    storageBucket: 'cleaner-application-27b56.firebasestorage.app',
    iosBundleId: 'com.example.cleanerapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhHaSWsOV2u7PmCsmeI8igiltJygiN2D8',
    appId: '1:728116934635:web:3101e6ad09c6e99e270bae',
    messagingSenderId: '728116934635',
    projectId: 'cleaner-application-27b56',
    authDomain: 'cleaner-application-27b56.firebaseapp.com',
    storageBucket: 'cleaner-application-27b56.firebasestorage.app',
  );
}
